apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-deployment-itzel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto-itzel
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: proyecto-itzel
        role: proyecto-itzel
    spec:
      containers:
        - name: proyecto-itzel
          image: itzelmunguia/proyecto:itz
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: proyecto-itzel


---
apiVersion: v1
kind: Service
metadata:
  name: proyecto-service-itzel
  labels:
    app: proyecto-itzel
spec:
  selector:
   app: proyecto-itzel
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: proyecto-itzel


